version: '3.7'

x-defaults: &defaults
  build: .
  environment:
    TZ: Asia/Tokyo
    EDITOR: vi
    APP_PATH: /app
    RAILS_ENV: development
  volumes:
    - .:/app
    - /app/tmp/cache
    - /app/tmp/pids
    - /app/.git
    - bundler-data:/usr/local/bundle

volumes:
  bundler-data:
  db-data:

services:
  web:
    <<: *defaults
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=mysecretpassword1234"
    tty: true
    stdin_open: true
    links:
      - db

  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/db-data
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=mysecretpassword1234"

  spring:
    <<: *defaults
    command: bundle exec spring server
      - db

#  guard:
#    <<: *defaults
#    command: bundle exec guard -i
#    depends_on:
#      - db
#      - cache
